Models/ErrorViewModel.cs
namespace Instruments.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/User.cs
using System.ComponentModel.DataAnnotations;

public class User
{
    public int Id { get; set; }
    [Required]
    [MaxLength(15)]
    public string FirstName { get; set; }
    [Required]
    [MaxLength(15)]
    public string LastName { get; set; }
    [Required]
    [DataType(DataType.PhoneNumber, ErrorMessage ="Siz telifon raqamingizni kiritmadingiz")]
    public string PhoneNumber { get; set; }
    [Required]
    [DataType(DataType.EmailAddress)]
    public string Email { get; set; }
    [Required]
    [DataType(DataType.Password)]
    [MaxLength(10)]
    [Range(5, 10, ErrorMessage ="Siz kiritgan parol 5 ta simvoldan 10 ta simvol oralig'ida bo'lishi kerak!")]
    public string Password { get; set; }
    [Required]
    [DataType(DataType.Password)]
    [MaxLength(10)]
    [Range(5, 10, ErrorMessage ="Siz kiritgan parol 5 ta simvoldan 10 ta simvol oralig'ida bo'lishi kerak!")]
    [Compare("Password", ErrorMessage ="Parolingiz to'g'ri kelmadi...")]
    public string PasswordConfirm { get; set; }
}

Controllers/AbbController.cs
using Microsoft.AspNetCore.Mvc;

namespace Instruments.Controllers;

public class AbbController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
    public IActionResult Pressure()
    {
        return View();
    }
     public IActionResult Flow()
    {
        return View();
    }
     public IActionResult Level()
    {
        return View();
    }
     public IActionResult Temperature()
    {
        return View();
    }
}

Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;

namespace Instruments.Controllers;

public class AuthController : Controller
{
    private readonly DataContext dbContext;

    public AuthController(DataContext dataContext)
    {
        this.dbContext = dataContext;
    }

    [HttpGet]
    public IActionResult Register()
    {
        return View();
    }

    [HttpPost]
    public IActionResult SendRegister(User user)
    {
        dbContext.Users.Add(user);
        dbContext.SaveChanges();


        List<Claim> claims = new List<Claim>()
        {
            new Claim(ClaimTypes.NameIdentifier, user.Email),
            new Claim("OtherProperties", "Example Role")
        };

        ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

        AuthenticationProperties properties = new AuthenticationProperties()
        {
            AllowRefresh = true,
            IsPersistent = true
        };
        
        HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), properties);

        return RedirectToAction("Index", "User");
    }

    [HttpGet]
    public IActionResult Login()
    {
        return View();
    }

    [HttpPost]
    public IActionResult SendLogin(User odam)
    {
        var user = dbContext.Users.FirstOrDefault(u=>u.Email==odam.Email && u.Password==odam.Password);
        
        List<Claim> claims = new List<Claim>()
        {
            new Claim(ClaimTypes.Email, odam.Email),
            new Claim("FirstName", user.FirstName),
            new Claim("OtherProperties", "Example Role")
        };

        ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

        AuthenticationProperties properties = new AuthenticationProperties()
        {
            AllowRefresh = true,
            IsPersistent = true
        };
        
        HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), properties);
        
        
        return RedirectToAction("Index", "Instrument");
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Instruments.Models;

namespace Instruments.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/InstrumentController.cs
using Microsoft.AspNetCore.Mvc;

namespace Instruments.Controllers;

public class InstrumentController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;

namespace Instruments.Controllers;

[Route("[controller]")]
public class UserController : Controller
{
    private readonly DataContext dbContext;

    public UserController(DataContext dataContext)
    {
        this.dbContext = dataContext;
    }

    [Route("[action]")]
    public IActionResult Index()
    {
        List<User> users = new List<User>();
        users = dbContext.Users.ToList();

        return View(users);
    }

    [Route("[action]")]
    [HttpGet]
    public IActionResult CreateUser()
    {
        return View();
    }

    [Route("[action]")]
    [HttpPost]
    public IActionResult Store(User user)
    {
        dbContext.Users.Add(user);
        dbContext.SaveChanges();

        return RedirectToAction("Index");
    }

    [HttpGet]
    [Route("[action]/{id}")]
    public IActionResult Edit(int id)
    {
        var user = dbContext.Users.Find(id);

        return View(user);
    }

    [HttpPost]
    [Route("[action]/{id}")]
    public IActionResult Update(User newuser, int id)
    {
        var olduser = dbContext.Users.Find(id);

        olduser.FirstName = newuser.FirstName;
        olduser.LastName = newuser.LastName;
        olduser.PhoneNumber = newuser.PhoneNumber;
        olduser.Email = newuser.Email;
        olduser.Password = newuser.Password;
        olduser.PasswordConfirm = newuser.PasswordConfirm;

        dbContext.SaveChanges();
        
        return RedirectToAction("Index");
    }
    
    [HttpGet]
    [Route("[action]/{id}")]
    public IActionResult Delete(int id)
    {
        var user = dbContext.Users.Find(id);
        dbContext.Users.Remove(user);
        dbContext.SaveChanges();

        return RedirectToAction("Index");
    }

}

Views/Home/Index.cshtml
@* @{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div> *@

Views/Instrument/Index.cshtml
@{
    Layout = "Instrument_Layout";
}


<h1>Nazorat O'lchov Asboblari va Avtomatlashtirish. Bu saytda sizga kerakli barcha ma'lumotlarni topa olasiz!!!</h1>

Views/Shared/Auth_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Instruments</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Instruments.styles.css" asp-append-version="true" />
</head>
<body style="background-image: url('https://mdbcdn.b-cdn.net/img/Photos/new-templates/search-box/img4.webp');">>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Instruments</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            @* <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a> *@
                        </li>
                        <li class="nav-item">
                            @* <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        @* <div class="container">
            &copy; 2024 - Instruments - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div> *@
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/Instrument_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Instruments</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Instruments.styles.css" asp-append-version="true" />
</head>
<body style="background-image: url('https://avatars.mds.yandex.net/get-altay/1483503/2a00000169807f640617a7c03a58d1cf6a56/orig'); size: ;">>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Instruments</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            @* <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a> *@
                        </li>
                        <li class="nav-item">
                            @* <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
                        </li>
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Instrument" asp-action="Index">Odam</a>
                        </li> *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Abb" asp-action="Index">ABB</a>
                        </li>

                    </ul>
                    <ul class="navbar-nav">
                            @if(User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="" asp-action="">@User.Claims.FirstOrDefault(x=>x.Type == System.Security.Claims.ClaimTypes.Email).Value</a>
                                </li>
                            }
                            else 
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Register">Register</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                                </li>
                            }
                            
                        </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        @* <div class="container">
            &copy; 2024 - Instruments - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div> *@
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Instruments</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Instruments.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Instruments</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            @* <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a> *@
                        </li>
                        <li class="nav-item">
                            @* <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Abb" asp-action="Index">ABB</a>
                        </li>
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User</a>
                        </li> *@
                    </ul>
                    <ul class="navbar-nav">
                            @if(User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="" asp-action="">@User.Claims.FirstOrDefault(x=>x.Type == System.Security.Claims.ClaimTypes.Email).Value</a>
                                </li>
                            }
                            else 
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Register">Register</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                                </li>
                            }
                            
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        @* <div class="container">
            &copy; 2024 - Instruments - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div> *@
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/User/CreateUser.cshtml
@model User;

@{
    ViewData["Title"]="Добавить user";
}

<div class="col-6">
    <form asp-controller="User" asp-action="Store" method="post">
        <div class="mb-3">
            <label for="FirstName">Ismingiz:</label>
            <input type="text" name="FirstName" class="form-control">
        </div>
        <div class="mb-3">
            <label for="LastName">Familiyangiz:</label>
            <input type="text" name="LastName" class="form-control">
        </div>
        <div class="mb-3">
            <label for="PhoneNumber">Telifon raqamingiz:</label>
            <input type="number" name="PhoneNumber" class="form-control">
        </div>
        <div class="mb-3">
            <label for="Email">Elektron pochtangiz:</label>
            <input type="email" name="Email" class="form-control">
        </div>
        <div class="mb-3">
            <label for="Password">Parolingiz:</label>
            <input type="number" name="Password" class="form-control">
        </div>
        <div class="mb-3">
            <label for="PasswordConfirm">Parolingizni qayta kiriting:</label>
            <input type="number" name="PasswordConfirm" class="form-control">
        </div>
        <button type="submit" class="btn btn-success">добавить</button>
    </form>
</div>

Views/User/Edit.cshtml
@model User;

@{
    ViewData["Title"]="Изминить user";
}

<div class="col-6">
    <form asp-controller="User" asp-action="Update" asp-route-id="@Model.Id" method="post">
       <div class="mb-3">
            <label for="FirstName">Ismingiz:</label>
            <input type="text" name="FirstName" class="form-control" value="@Model.FirstName">
        </div>
        <div class="mb-3">
            <label for="LastName">Familiyangiz:</label>
            <input type="text" name="LastName" class="form-control" value="@Model.LastName">
        </div>
        <div class="mb-3">
            <label for="PhoneNumber">Telifon raqamingiz:</label>
            <input type="number" name="PhoneNumber" class="form-control" value="@Model.PhoneNumber">
        </div>
        <div class="mb-3">
            <label for="Email">Elektron pochtangiz:</label>
            <input type="email" name="Email" class="form-control" value="@Model.Email">
        </div>
        <div class="mb-3">
            <label for="Password">Parolingiz:</label>
            <input type="password" name="Password" class="form-control" value="@Model.Password">
        </div>
        <div class="mb-3">
            <label for="PasswordConfirm">Parolingizni qayta kiriting:</label>
            <input type="password" name="PasswordConfirm" class="form-control" value="@Model.PasswordConfirm">
        </div>
        <button type="submit" class="btn btn-success">добавить</button>
    </form>
</div>

Views/User/Index.cshtml
@model List<User>

    @{
        ViewData["Title"]="Списка user";
    }

<table class="table">
    <tr>
        <th>Id</th>
        <th>FirstName</th>
        <th>LastName</th>
        <th>PhoneNumber</th>
        <th>Email</th>
        <th>Password</th>
        <th>PasswordConfirm</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    @foreach(var user in Model)
    {
        <tr>
            <td>@user.Id</td>
            <td>@user.FirstName</td>
             <td>@user.LastName</td>
            <td>@user.PhoneNumber</td>
            <td>@user.Email</td>
            <td>@user.Password</td>
            <td>@user.PasswordConfirm</td>
            <td><a asp-controller="User" asp-action="Edit" asp-route-id="@user.Id">Изминить</a></td>
            <td><a asp-controller="User" asp-action="Delete" asp-route-id="@user.Id">Удалить</a></td>
        </tr>
    }
</table>

<button class="btn btn-outline-danger"><a asp-controller="User" asp-action="CreateUser">Create User</a></button>